version: '3.3'

networks:
    example:
      driver: bridge

services:
  example_nginx:
    container_name: example_nginx
    image: nginx:stable-alpine
    ports:
      - 8093:8093
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www
    depends_on:
      - example_app
    networks:
      - example

  example_app:
    container_name: example_app
    build:
      context: ./docker/php
      dockerfile: Dockerfile.prod
    tty: true
    volumes:
      - ./docker/php/php-fpm.d:/usr/local/etc/php-fpm:ro
      - ./:/var/www
      - ./docker/php/prod.ini:/usr/local/etc/php/conf.d/my.ini
    depends_on:
      - example_db
    networks:
      - example

  example_db:
    container_name: example_db
    image: mysql:8
    ports:
      - 13307:3306
    volumes:
      - ./docker/mysql/storage:/var/lib/mysql
      - ./docker/mysql/backup:/var/db
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: example
      MYSQL_USER: developer
    networks:
      - example
