<?php declare(strict_types=1);

namespace App\Http\Requests\Pay;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Class PayLinkRequest
 */
class PayLinkRequest extends FormRequest
{
    public function rules()
    {
        return [
          'email' => 'required|email',
          'sum' => 'required|numeric',
          'product.name' => 'required|string|min:2|max:255',
          'product.description' => 'nullable|string|min:2|max:255',
          'urls.success' => 'required|string|max:255',
          'urls.error' => 'required|string|max:255',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
