<?php declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Payment
 * @package App\Models
 */
class Payment extends Model
{
    const STATUS_PENDING = 0;
    const STATUS_FAILED = 2;
    const STATUS_SUCCESS = 1;

    protected array $attributes = [
        'external_id' => '',
        'product_name' => '',
        'description' => '',
        'payment_system' => '',
        'status' => self::STATUS_PENDING,
    ];

    protected array $fillable = [
        'external_id',
        'status',
        'product_name',
        'payment_system',
        'description',
    ];

    protected array $visible = [
        'id',
        'status',
        'description',
        'payment_system',
        'product_name',
    ];

    /**
     * @return string
     */
    public function getTable(): string
    {
        return 'payments'; // TODO: Change the autogenerated stub
    }
}
